from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from krs.simulation.experiment import ExperimentResult
from krs.simulation.runner import GoldfishRunResult


CsvRow = dict[str, Any]


@dataclass(frozen=True, slots=True)
class CsvReportPaths:
    """
    Stores the paths generated by one CSV report operation.
    """

    summary_path: Path
    games_path: Path


@dataclass(frozen=True, slots=True)
class CsvExperimentReporter:
    """
    Writes ExperimentResult data to summary and per-game CSV files.

    The reporter only serializes existing configuration, summary, and game
    results. It does not recalculate statistics or modify ExperimentResult.
    """

    summary_filename: str = "summary.csv"
    games_filename: str = "games.csv"

    def __post_init__(self) -> None:
        self._validate_filename(
            self.summary_filename,
            field_name="summary_filename",
        )
        self._validate_filename(
            self.games_filename,
            field_name="games_filename",
        )

        if self.summary_filename == self.games_filename:
            raise ValueError(
                "summary_filename and games_filename must be different."
            )

    def write(
        self,
        result: ExperimentResult,
        directory: str | Path,
    ) -> CsvReportPaths:
        """
        Write summary.csv and games.csv into the supplied directory.

        Missing directories are created automatically.
        """
        output_directory = Path(directory)

        if output_directory.exists() and not output_directory.is_dir():
            raise ValueError(
                "CSV report output path is not a directory: "
                f"{output_directory}"
            )

        output_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        summary_path = (
            output_directory
            / self.summary_filename
        )
        games_path = (
            output_directory
            / self.games_filename
        )

        self.write_summary(
            result,
            summary_path,
        )
        self.write_games(
            result,
            games_path,
        )

        return CsvReportPaths(
            summary_path=summary_path,
            games_path=games_path,
        )

    def write_summary(
        self,
        result: ExperimentResult,
        path: str | Path,
    ) -> Path:
        """
        Write one-row experiment configuration and summary data.
        """
        output_path = self._prepare_file_path(
            path,
        )
        row = self._summary_row(result)

        with output_path.open(
            "w",
            encoding="utf-8",
            newline="",
        ) as file:
            writer = csv.DictWriter(
                file,
                fieldnames=list(row),
                lineterminator="\n",
            )
            writer.writeheader()
            writer.writerow(row)

        return output_path

    def write_games(
        self,
        result: ExperimentResult,
        path: str | Path,
    ) -> Path:
        """
        Write all individual Goldfish game results in game ID order.
        """
        output_path = self._prepare_file_path(
            path,
        )

        fieldnames = [
            "game_id",
            "turns_started",
            "kinnan_activations",
            "reached_turn_limit",
            "game_over",
            "winner",
        ]

        with output_path.open(
            "w",
            encoding="utf-8",
            newline="",
        ) as file:
            writer = csv.DictWriter(
                file,
                fieldnames=fieldnames,
                lineterminator="\n",
            )
            writer.writeheader()

            writer.writerows(
                self._game_row(
                    game_id=game_id,
                    result=game_result,
                )
                for game_id, game_result in enumerate(
                    result.game_results
                )
            )

        return output_path

    @staticmethod
    def _summary_row(
        result: ExperimentResult,
    ) -> CsvRow:
        """
        Convert configuration and summary values into one CSV row.
        """
        config = result.config
        summary = result.summary

        return {
            "strategy_name": config.strategy_name,
            "games": config.games,
            "max_turns": config.max_turns,
            "seed": (
                ""
                if config.seed is None
                else config.seed
            ),
            "mulligan_enabled": config.mulligan_enabled,
            "save_replays": config.save_replays,
            "workers": config.workers,
            "games_requested": summary.games_requested,
            "games_completed": summary.games_completed,
            "wins": summary.wins,
            "non_wins": summary.non_wins,
            "win_rate": summary.win_rate,
            "turn_limit_games": summary.turn_limit_games,
            "total_turns_started": summary.total_turns_started,
            "average_turns_started": (
                summary.average_turns_started
            ),
            "total_kinnan_activations": (
                summary.total_kinnan_activations
            ),
            "average_kinnan_activations": (
                summary.average_kinnan_activations
            ),
            "fastest_win_turn": (
                ""
                if summary.fastest_win_turn is None
                else summary.fastest_win_turn
            ),
        }

    @staticmethod
    def _game_row(
        *,
        game_id: int,
        result: GoldfishRunResult,
    ) -> CsvRow:
        """
        Convert one GoldfishRunResult into a CSV row.
        """
        return {
            "game_id": game_id,
            "turns_started": result.turns_started,
            "kinnan_activations": result.kinnan_activations,
            "reached_turn_limit": result.reached_turn_limit,
            "game_over": result.game_over,
            "winner": (
                ""
                if result.winner is None
                else result.winner
            ),
        }

    @staticmethod
    def _prepare_file_path(
        path: str | Path,
    ) -> Path:
        """
        Validate a CSV file path and create its parent directories.
        """
        output_path = Path(path)

        if output_path.exists() and output_path.is_dir():
            raise ValueError(
                f"CSV report path is a directory: {output_path}"
            )

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        return output_path

    @staticmethod
    def _validate_filename(
        filename: str,
        *,
        field_name: str,
    ) -> None:
        """
        Validate that a configured output name is a plain CSV filename.
        """
        if not filename.strip():
            raise ValueError(
                f"{field_name} must not be empty."
            )

        filename_path = Path(filename)

        if filename_path.name != filename:
            raise ValueError(
                f"{field_name} must not contain a directory."
            )

        if filename_path.suffix.casefold() != ".csv":
            raise ValueError(
                f"{field_name} must use the .csv extension."
            )